name: Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: tau-OS/github-actions/.github/workflows/build-rpm.yml@main
    with:
      name: "tau-dash-to-dock"
  sign:
    needs:
      - build
    uses: tau-OS/github-actions/.github/workflows/sign-rpm.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      name: "tau-dash-to-dock"
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  upload:
    needs:
      - sign
    uses: tau-OS/github-actions/.github/workflows/upload-rpm.yml@main
    with:
      name: "tau-dash-to-dock"
      tauOSVersion: "1"
    secrets:
      repoIP: ${{ secrets.REPO_IP }}
      repoKnownHosts: ${{ secrets.REPO_KNOWN_HOSTS }}
      repoPrivateKey: ${{ secrets.REPO_PRIVATE_KEY }}
